import type { LucideIcon } from 'lucide-react';
import {
  HeartPulse,
  RefreshCw,
  ShieldCheck,
  Activity,
  BookOpen,
  Heart,
  Stethoscope,
  Syringe,
  Pill,
  Thermometer,
  BriefcaseMedical,
  Bandage,
  Ambulance,
  Hospital,
  Baby,
  Bone,
  Brain,
  Hand,
  Dna,
  Microscope,
  HeartHandshake,
  Cross,
  HeartCrack,
  ShieldAlert,
  Shield,
  ShieldQuestion,
  ShieldPlus,
  AlertTriangle,
  AlertCircle,
  AlertOctagon,
  LifeBuoy,
  Flame,
  Zap,
  ZapOff,
  Siren,
  PhoneCall,
  Radio,
  HelpCircle,
  Info,
  Bell,
  BellRing,
  RefreshCcw,
  RotateCw,
  Clock,
  Watch,
  Timer,
  TimerReset,
  Calendar,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  History,
  Hourglass,
  BookMarked,
  Bookmark,
  Book,
  Award,
  Medal,
  GraduationCap,
  Trophy,
  FileCheck,
  BadgeCheck,
  BadgeAlert,
  BadgeInfo,
  BadgePercent,
  Badge,
  FileText,
  File,
  FilePlus,
  ClipboardCheck,
  ClipboardList,
  ListChecks,
  FolderCheck,
  Folder,
  CheckCircle,
  CheckCircle2,
  CheckCheck,
  CheckSquare,
  FileBadge,
  Scroll,
  Library,
  HardHat,
  Eye,
  Glasses,
  Ear,
  Wrench,
  Hammer,
  Building,
  Building2,
  Factory,
  Home,
  School,
  Truck,
  Scale,
  Anchor,
  Footprints,
  Luggage,
  Users,
  UserCheck,
  UserPlus,
  User,
  UserCog,
  Sparkles,
  Star,
  Smile,
  Compass,
  Target,
  Presentation,
  Laptop,
  Video,
  Layers,
  Lightbulb,
  MapPin,
  Navigation,
  Phone,
  Car,
  Briefcase,
  Check,
  CircleDot,
  FileQuestion,
  Globe,
  Headphones,
  Lock,
  ShieldX,
  Sparkle,
  ThumbsUp,
  UserRound,
  UsersRound,
  Volume2,
  Waves,
  Contact,
  Inbox,
  Key,
  Megaphone,
  MessageCircle,
  MessageSquare,
  Mic,
  MousePointer,
  Network,
  PenTool,
  Printer,
  QrCode,
  Ribbon,
  Search,
  Share2,
  Sliders,
  Sun,
  Tag,
  Unlock,
  Upload,
  Wallet,
  Wind,
  CircleCheck,
  CircleHelp,
  CircleAlert,
  IdCard,
  MonitorCheck,
  ScanLine,
} from 'lucide-react';

export const DEFAULT_COURSE_ICON = 'BookOpen';

export interface IconDefinition {
  name: string;
  component: LucideIcon;
  category: 'medical' | 'safety' | 'time' | 'certification' | 'workplace' | 'general';
  tags: string[];
}

export const COURSE_ICONS: IconDefinition[] = [
  // Medical & Healthcare
  { name: 'HeartPulse', component: HeartPulse, category: 'medical', tags: ['cpr', 'bls', 'pulse', 'heart', 'cardiac', 'life', 'medical'] },
  { name: 'Activity', component: Activity, category: 'medical', tags: ['emergency', 'ecg', 'heartbeat', 'monitor', 'vital', 'medical'] },
  { name: 'Heart', component: Heart, category: 'medical', tags: ['love', 'care', 'health', 'cardio', 'life'] },
  { name: 'HeartHandshake', component: HeartHandshake, category: 'medical', tags: ['care', 'helping', 'support', 'trust', 'counseling'] },
  { name: 'HeartCrack', component: HeartCrack, category: 'medical', tags: ['attack', 'cardiac arrest', 'heart condition'] },
  { name: 'BriefcaseMedical', component: BriefcaseMedical, category: 'medical', tags: ['first aid kit', 'doctor', 'kit', 'medical bag', 'emergency'] },
  { name: 'Bandage', component: Bandage, category: 'medical', tags: ['wound', 'injury', 'first aid', 'patch', 'dressing'] },
  { name: 'Cross', component: Cross, category: 'medical', tags: ['red cross', 'hospital', 'clinic', 'first aid', 'medical'] },
  { name: 'Stethoscope', component: Stethoscope, category: 'medical', tags: ['doctor', 'nurse', 'exam', 'clinic', 'healthcare'] },
  { name: 'Syringe', component: Syringe, category: 'medical', tags: ['injection', 'vaccine', 'needle', 'medicine'] },
  { name: 'Pill', component: Pill, category: 'medical', tags: ['medication', 'pharmacy', 'prescription', 'drugs'] },
  { name: 'Thermometer', component: Thermometer, category: 'medical', tags: ['temperature', 'fever', 'vitals', 'check'] },
  { name: 'Baby', component: Baby, category: 'medical', tags: ['infant', 'pediatric', 'child', 'cpr', 'choking'] },
  { name: 'Bone', component: Bone, category: 'medical', tags: ['fracture', 'break', 'splint', 'anatomy'] },
  { name: 'Brain', component: Brain, category: 'medical', tags: ['stroke', 'neurology', 'head injury', 'concussion', 'mind'] },
  { name: 'Hand', component: Hand, category: 'medical', tags: ['touch', 'handwashing', 'hygiene', 'hands-on', 'compression'] },
  { name: 'Hospital', component: Hospital, category: 'medical', tags: ['clinic', 'emergency room', 'er', 'healthcare facility'] },
  { name: 'Ambulance', component: Ambulance, category: 'medical', tags: ['paramedic', 'ems', 'transport', 'emergency vehicle'] },
  { name: 'Microscope', component: Microscope, category: 'medical', tags: ['lab', 'research', 'testing', 'science'] },
  { name: 'Dna', component: Dna, category: 'medical', tags: ['genetics', 'biology', 'science'] },

  // Safety & Emergency
  { name: 'ShieldCheck', component: ShieldCheck, category: 'safety', tags: ['standard', 'safety', 'first aid', 'protect', 'secure', 'verified'] },
  { name: 'Shield', component: Shield, category: 'safety', tags: ['protection', 'defense', 'security'] },
  { name: 'ShieldAlert', component: ShieldAlert, category: 'safety', tags: ['warning', 'hazard', 'alert', 'protection'] },
  { name: 'ShieldPlus', component: ShieldPlus, category: 'safety', tags: ['health safety', 'first aid', 'extra protection'] },
  { name: 'ShieldQuestion', component: ShieldQuestion, category: 'safety', tags: ['risk assessment', 'safety inquiry'] },
  { name: 'ShieldX', component: ShieldX, category: 'safety', tags: ['danger', 'unsafe', 'hazard'] },
  { name: 'AlertTriangle', component: AlertTriangle, category: 'safety', tags: ['warning', 'danger', 'hazard', 'caution', 'emergency'] },
  { name: 'AlertCircle', component: AlertCircle, category: 'safety', tags: ['notice', 'attention', 'warning'] },
  { name: 'AlertOctagon', component: AlertOctagon, category: 'safety', tags: ['stop', 'critical warning', 'danger'] },
  { name: 'Flame', component: Flame, category: 'safety', tags: ['fire', 'burns', 'hot', 'fire safety', 'extinguisher'] },
  { name: 'Zap', component: Zap, category: 'safety', tags: ['aed', 'defibrillator', 'electric shock', 'power', 'lightning'] },
  { name: 'ZapOff', component: ZapOff, category: 'safety', tags: ['power cut', 'electrical safety'] },
  { name: 'LifeBuoy', component: LifeBuoy, category: 'safety', tags: ['lifeguard', 'water safety', 'rescue', 'drowning', 'swim'] },
  { name: 'Waves', component: Waves, category: 'safety', tags: ['water', 'ocean', 'pool', 'aquatic safety'] },
  { name: 'Siren', component: Siren, category: 'safety', tags: ['alarm', 'police', 'ambulance', 'emergency siren'] },
  { name: 'Bell', component: Bell, category: 'safety', tags: ['alarm', 'notify', 'alert', 'chime'] },
  { name: 'BellRing', component: BellRing, category: 'safety', tags: ['ringing alarm', 'dispatch', 'urgent'] },
  { name: 'PhoneCall', component: PhoneCall, category: 'safety', tags: ['911', 'call', 'dispatch', 'emergency contact'] },
  { name: 'Radio', component: Radio, category: 'safety', tags: ['walkie talkie', 'dispatch', 'communication', 'ems'] },

  // Renewal & Time
  { name: 'RefreshCw', component: RefreshCw, category: 'time', tags: ['renewal', 'recertification', 'repeat', 'update', 'sync'] },
  { name: 'RefreshCcw', component: RefreshCcw, category: 'time', tags: ['reverse', 'reload', 'cycle'] },
  { name: 'RotateCw', component: RotateCw, category: 'time', tags: ['renew', 'rotation', 'turn'] },
  { name: 'Clock', component: Clock, category: 'time', tags: ['time', 'duration', 'hours', 'schedule'] },
  { name: 'Timer', component: Timer, category: 'time', tags: ['stopwatch', 'speed', 'minutes', 'countdown'] },
  { name: 'TimerReset', component: TimerReset, category: 'time', tags: ['restart', 'reset time'] },
  { name: 'Watch', component: Watch, category: 'time', tags: ['wrist watch', 'pulse timing', 'seconds'] },
  { name: 'Hourglass', component: Hourglass, category: 'time', tags: ['deadline', 'expiration', 'validity'] },
  { name: 'History', component: History, category: 'time', tags: ['past', 'record', 'previous cert'] },
  { name: 'Calendar', component: Calendar, category: 'time', tags: ['date', 'booking', 'schedule', 'annual'] },
  { name: 'CalendarCheck', component: CalendarCheck, category: 'time', tags: ['scheduled', 'booked', 'confirmed'] },
  { name: 'CalendarClock', component: CalendarClock, category: 'time', tags: ['appointment', 'timing', 'duration'] },
  { name: 'CalendarDays', component: CalendarDays, category: 'time', tags: ['multi-day', 'events', 'schedule'] },

  // Certification, Education & Training
  { name: 'BookOpen', component: BookOpen, category: 'certification', tags: ['training', 'course', 'curriculum', 'education', 'study'] },
  { name: 'Book', component: Book, category: 'certification', tags: ['textbook', 'handbook', 'manual', 'guidelines'] },
  { name: 'BookMarked', component: BookMarked, category: 'certification', tags: ['reference', 'bookmark', 'protocol'] },
  { name: 'Bookmark', component: Bookmark, category: 'certification', tags: ['save', 'tag', 'standard'] },
  { name: 'Library', component: Library, category: 'certification', tags: ['knowledge', 'academy', 'institution'] },
  { name: 'Award', component: Award, category: 'certification', tags: ['certification', 'certificate', 'accredited', 'ribbon', 'diploma'] },
  { name: 'Medal', component: Medal, category: 'certification', tags: ['achievement', 'honor', 'standard'] },
  { name: 'Trophy', component: Trophy, category: 'certification', tags: ['winner', 'excellence', 'qualification'] },
  { name: 'GraduationCap', component: GraduationCap, category: 'certification', tags: ['graduate', 'degree', 'passed', 'alumni'] },
  { name: 'BadgeCheck', component: BadgeCheck, category: 'certification', tags: ['verified certificate', 'badge', 'approved'] },
  { name: 'BadgeAlert', component: BadgeAlert, category: 'certification', tags: ['expiring badge', 'status'] },
  { name: 'BadgeInfo', component: BadgeInfo, category: 'certification', tags: ['badge info', 'details'] },
  { name: 'BadgePercent', component: BadgePercent, category: 'certification', tags: ['passing score', 'grade'] },
  { name: 'Badge', component: Badge, category: 'certification', tags: ['emblem', 'shield', 'insignia'] },
  { name: 'FileBadge', component: FileBadge, category: 'certification', tags: ['certified document', 'credential', 'official certificate'] },
  { name: 'FileCheck', component: FileCheck, category: 'certification', tags: ['passed test', 'verified', 'completion'] },
  { name: 'FileText', component: FileText, category: 'certification', tags: ['document', 'syllabus', 'records', 'notes'] },
  { name: 'File', component: File, category: 'certification', tags: ['paper', 'form', 'worksheet'] },
  { name: 'FilePlus', component: FilePlus, category: 'certification', tags: ['add document', 'new form'] },
  { name: 'FileQuestion', component: FileQuestion, category: 'certification', tags: ['exam', 'test', 'quiz'] },
  { name: 'ClipboardCheck', component: ClipboardCheck, category: 'certification', tags: ['checklist', 'skills test', 'evaluation', 'audit'] },
  { name: 'ClipboardList', component: ClipboardList, category: 'certification', tags: ['inventory', 'procedures', 'steps'] },
  { name: 'ListChecks', component: ListChecks, category: 'certification', tags: ['requirements', 'prerequisites', 'completed'] },
  { name: 'FolderCheck', component: FolderCheck, category: 'certification', tags: ['approved folder', 'records kept'] },
  { name: 'Folder', component: Folder, category: 'certification', tags: ['archive', 'directory'] },
  { name: 'CheckCircle', component: CheckCircle, category: 'certification', tags: ['passed', 'success', 'approved', 'complete'] },
  { name: 'CheckCircle2', component: CheckCircle2, category: 'certification', tags: ['verified', 'correct', 'done'] },
  { name: 'CircleCheck', component: CircleCheck, category: 'certification', tags: ['ok', 'check', 'certified'] },
  { name: 'CheckCheck', component: CheckCheck, category: 'certification', tags: ['double check', 'verified', 'read'] },
  { name: 'Check', component: Check, category: 'certification', tags: ['tick', 'yes', 'valid'] },
  { name: 'CheckSquare', component: CheckSquare, category: 'certification', tags: ['checkbox', 'completed task'] },
  { name: 'Scroll', component: Scroll, category: 'certification', tags: ['diploma', 'decree', 'ancient certificate'] },
  { name: 'IdCard', component: IdCard, category: 'certification', tags: ['license', 'wallet card', 'credential', 'id'] },
  { name: 'Ribbon', component: Ribbon, category: 'certification', tags: ['awareness', 'honor', 'cause'] },

  // Workplace, Trades & Industry
  { name: 'HardHat', component: HardHat, category: 'workplace', tags: ['construction', 'workplace safety', 'osha', 'contractor', 'trades'] },
  { name: 'Eye', component: Eye, category: 'workplace', tags: ['eye protection', 'eye wash', 'vision', 'hazard'] },
  { name: 'Glasses', component: Glasses, category: 'workplace', tags: ['safety glasses', 'ppe', 'eyewear'] },
  { name: 'Ear', component: Ear, category: 'workplace', tags: ['hearing protection', 'earplugs', 'noise'] },
  { name: 'Wrench', component: Wrench, category: 'workplace', tags: ['tools', 'maintenance', 'mechanic', 'repair'] },
  { name: 'Hammer', component: Hammer, category: 'workplace', tags: ['carpentry', 'construction', 'labor'] },
  { name: 'Building', component: Building, category: 'workplace', tags: ['office', 'corporate', 'workplace'] },
  { name: 'Building2', component: Building2, category: 'workplace', tags: ['headquarters', 'facility', 'company'] },
  { name: 'Factory', component: Factory, category: 'workplace', tags: ['industrial', 'manufacturing', 'plant', 'warehouse'] },
  { name: 'Home', component: Home, category: 'workplace', tags: ['family', 'residential', 'home first aid', 'babysitter'] },
  { name: 'School', component: School, category: 'workplace', tags: ['teachers', 'daycare', 'students', 'education'] },
  { name: 'Truck', component: Truck, category: 'workplace', tags: ['drivers', 'fleet', 'transport', 'commercial'] },
  { name: 'Car', component: Car, category: 'workplace', tags: ['vehicle', 'auto', 'road safety'] },
  { name: 'Anchor', component: Anchor, category: 'workplace', tags: ['marine', 'boating', 'nautical'] },
  { name: 'Briefcase', component: Briefcase, category: 'workplace', tags: ['business', 'professional', 'office'] },
  { name: 'Luggage', component: Luggage, category: 'workplace', tags: ['travel', 'tourism', 'flight'] },
  { name: 'Footprints', component: Footprints, category: 'workplace', tags: ['outdoor', 'hiking', 'wilderness first aid'] },
  { name: 'Scale', component: Scale, category: 'workplace', tags: ['legal', 'compliance', 'regulations', 'standards'] },

  // People, Communication & General
  { name: 'Users', component: Users, category: 'general', tags: ['group training', 'team', 'class', 'corporate group'] },
  { name: 'UsersRound', component: UsersRound, category: 'general', tags: ['people', 'community', 'public'] },
  { name: 'UserCheck', component: UserCheck, category: 'general', tags: ['qualified provider', 'authorized', 'enrolled'] },
  { name: 'UserPlus', component: UserPlus, category: 'general', tags: ['register', 'add student', 'enrollment'] },
  { name: 'User', component: User, category: 'general', tags: ['individual', 'person', 'student'] },
  { name: 'UserRound', component: UserRound, category: 'general', tags: ['avatar', 'profile'] },
  { name: 'UserCog', component: UserCog, category: 'general', tags: ['instructor', 'trainer', 'admin'] },
  { name: 'Sparkles', component: Sparkles, category: 'general', tags: ['featured', 'premium', 'popular', 'new'] },
  { name: 'Sparkle', component: Sparkle, category: 'general', tags: ['shine', 'highlight'] },
  { name: 'Star', component: Star, category: 'general', tags: ['rating', 'top course', 'favorite'] },
  { name: 'Smile', component: Smile, category: 'general', tags: ['friendly', 'confidence', 'mental health'] },
  { name: 'ThumbsUp', component: ThumbsUp, category: 'general', tags: ['recommended', 'approved', 'great'] },
  { name: 'Compass', component: Compass, category: 'general', tags: ['navigation', 'guidance', 'orientation'] },
  { name: 'Target', component: Target, category: 'general', tags: ['goals', 'skills benchmark', 'accuracy'] },
  { name: 'Presentation', component: Presentation, category: 'general', tags: ['lecture', 'workshop', 'seminar'] },
  { name: 'Laptop', component: Laptop, category: 'general', tags: ['blended learning', 'online course', 'e-learning'] },
  { name: 'Video', component: Video, category: 'general', tags: ['video demonstration', 'webinar', 'virtual'] },
  { name: 'MonitorCheck', component: MonitorCheck, category: 'general', tags: ['online test passed', 'computer training'] },
  { name: 'Layers', component: Layers, category: 'general', tags: ['modules', 'levels', 'steps', 'levels A/C'] },
  { name: 'Lightbulb', component: Lightbulb, category: 'general', tags: ['tips', 'ideas', 'quick facts', 'learning'] },
  { name: 'MapPin', component: MapPin, category: 'general', tags: ['location', 'on-site training', 'facility'] },
  { name: 'Navigation', component: Navigation, category: 'general', tags: ['directions', 'travel to site'] },
  { name: 'Phone', component: Phone, category: 'general', tags: ['contact', 'telephone', 'inquiries'] },
  { name: 'HelpCircle', component: HelpCircle, category: 'general', tags: ['faq', 'questions', 'support'] },
  { name: 'CircleHelp', component: CircleHelp, category: 'general', tags: ['help', 'info', 'assistance'] },
  { name: 'Info', component: Info, category: 'general', tags: ['details', 'information', 'note'] },
  { name: 'CircleAlert', component: CircleAlert, category: 'general', tags: ['alert', 'attention'] },
  { name: 'CircleDot', component: CircleDot, category: 'general', tags: ['bullet', 'target', 'dot'] },
  { name: 'Globe', component: Globe, category: 'general', tags: ['international', 'world standards', 'wide'] },
  { name: 'Headphones', component: Headphones, category: 'general', tags: ['audio', 'listen', 'support'] },
  { name: 'Lock', component: Lock, category: 'general', tags: ['secure', 'privacy', 'confidential'] },
  { name: 'Unlock', component: Unlock, category: 'general', tags: ['accessible', 'open access'] },
  { name: 'Volume2', component: Volume2, category: 'general', tags: ['aed voice prompts', 'sound', 'audio instruction'] },
  { name: 'Contact', component: Contact, category: 'general', tags: ['address book', 'instructor', 'reach out'] },
  { name: 'Inbox', component: Inbox, category: 'general', tags: ['messages', 'inbox'] },
  { name: 'Key', component: Key, category: 'general', tags: ['key takeaway', 'essential skills'] },
  { name: 'Megaphone', component: Megaphone, category: 'general', tags: ['announcement', 'loud alert'] },
  { name: 'MessageCircle', component: MessageCircle, category: 'general', tags: ['chat', 'feedback'] },
  { name: 'MessageSquare', component: MessageSquare, category: 'general', tags: ['discussion', 'questions'] },
  { name: 'Mic', component: Mic, category: 'general', tags: ['speaking', 'instruction'] },
  { name: 'MousePointer', component: MousePointer, category: 'general', tags: ['interactive', 'click to learn'] },
  { name: 'Network', component: Network, category: 'general', tags: ['organization', 'network'] },
  { name: 'PenTool', component: PenTool, category: 'general', tags: ['design', 'craft'] },
  { name: 'Printer', component: Printer, category: 'general', tags: ['print certificate', 'materials'] },
  { name: 'QrCode', component: QrCode, category: 'general', tags: ['digital card', 'qr verify', 'scan cert'] },
  { name: 'ScanLine', component: ScanLine, category: 'general', tags: ['scan', 'barcode', 'digital badge'] },
  { name: 'Search', component: Search, category: 'general', tags: ['find course', 'lookup'] },
  { name: 'Share2', component: Share2, category: 'general', tags: ['share course', 'tell others'] },
  { name: 'Sliders', component: Sliders, category: 'general', tags: ['customized', 'flexible options'] },
  { name: 'Sun', component: Sun, category: 'general', tags: ['heat exhaustion', 'outdoor', 'sunstroke'] },
  { name: 'Tag', component: Tag, category: 'general', tags: ['pricing', 'label', 'category'] },
  { name: 'Upload', component: Upload, category: 'general', tags: ['upload proof', 'prerequisite upload'] },
  { name: 'Wallet', component: Wallet, category: 'general', tags: ['payment', 'wallet card'] },
  { name: 'Wind', component: Wind, category: 'general', tags: ['breathing', 'ventilation', 'airway'] },
];

// Quick lookup map: name -> component
export const COURSE_ICON_MAP: Record<string, LucideIcon> = COURSE_ICONS.reduce((acc, curr) => {
  acc[curr.name] = curr.component;
  return acc;
}, {} as Record<string, LucideIcon>);

// Migration fallback mapping for legacy course IDs if icon field is not yet set
const LEGACY_ID_MAP: Record<string, string> = {
  'bls-provider': 'HeartPulse',
  'bls-renewal': 'RefreshCw',
  'standard-first-aid-cpr-c': 'ShieldCheck',
  'emergency-first-aid': 'Activity',
};

/**
 * Safely resolves any icon name or legacy course ID to a Lucide icon component.
 * Invalid or missing icon names gracefully fall back to BookOpen.
 */
export const resolveCourseIcon = (nameOrId?: string): LucideIcon => {
  if (!nameOrId) {
    return COURSE_ICON_MAP[DEFAULT_COURSE_ICON] || BookOpen;
  }

  // 1. Direct match in icon registry
  if (COURSE_ICON_MAP[nameOrId]) {
    return COURSE_ICON_MAP[nameOrId];
  }

  // 2. Legacy course ID mapping
  const legacyMapped = LEGACY_ID_MAP[nameOrId];
  if (legacyMapped && COURSE_ICON_MAP[legacyMapped]) {
    return COURSE_ICON_MAP[legacyMapped];
  }

  // 3. Fallback to default
  return COURSE_ICON_MAP[DEFAULT_COURSE_ICON] || BookOpen;
};

/**
 * Checks whether an icon name is valid and supported by the registry.
 */
export const isSupportedCourseIcon = (name?: string): boolean => {
  if (!name) return false;
  return Boolean(COURSE_ICON_MAP[name]);
};
